/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Hotel.DAO.ClienteDAO;
import Hotel.DAO.EmpleadoDAO;
import Hotel.DAO.FacturaDAO;
import Hotel.DAO.HabitacionDAO;
import Hotel.DAO.ServicioAdicionalDAO;
import Hotel.DTO.Cliente;
import Hotel.DTO.Empleado;
import Hotel.DTO.Factura;
import Hotel.DTO.Habitacion;
import Hotel.DTO.ServicioAdicional;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boris
 */
public class VentanaRegistroFactura extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroFactura
     */
    ClienteDAO clienteDao = new ClienteDAO();
    EmpleadoDAO empleadoDao = new EmpleadoDAO();
    HabitacionDAO habitacionDao = new HabitacionDAO();
    ServicioAdicionalDAO servicioDao = new ServicioAdicionalDAO();
    FacturaDAO facturaDao = new FacturaDAO();

    List<Habitacion> listaHabitacionesCombo = new ArrayList<>();
    ArrayList<Hotel.DTO.Empleado> listaEmpleadosCombo = new ArrayList<>();
    ArrayList<ServicioAdicional> serviciosSeleccionados = new ArrayList<>();
    double totalVisual = 0.0;
    
    public VentanaRegistroFactura() {
        initComponents();
        this.setTitle("Registro de Nueva Factura - Hotel Grupo 1");
        cargarCombos();
        inicializarTabla();
    }
    
    private void inicializarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Categoria");
        model.addColumn("Descripción");
        model.addColumn("Precio");
        model.setRowCount(0); 
        
        tblServicios.setModel(model);
    }
    
    private void cargarCombos() {
        javax.swing.DefaultComboBoxModel modelCli = new javax.swing.DefaultComboBoxModel();
        for (Hotel.DTO.Cliente c : clienteDao.listar()) {
            modelCli.addElement(c);
        }
        cbxCliente.setModel(modelCli);
        cbxEmpleado.removeAllItems(); 
        listaEmpleadosCombo.clear();  
        for (Hotel.DTO.Empleado e : empleadoDao.leerTodos()) {
            String texto = e.getNombre() + " " + e.getApellido() + " (" + e.getCargo() + ")";
            cbxEmpleado.addItem(texto);
            listaEmpleadosCombo.add(e);
        }
        cbxHabitacion.removeAllItems();
        listaHabitacionesCombo.clear();

        java.util.List<Hotel.DTO.Habitacion> habitaciones = habitacionDao.leerHabitaciones();
        
        for (Hotel.DTO.Habitacion h : habitaciones) {
            if(h.getEstado().equalsIgnoreCase("Disponible")){
                String texto = "Hab: " + h.getNumeroHabitacion() + " - $" + h.getPrecioxNoche();
                cbxHabitacion.addItem(texto);
                listaHabitacionesCombo.add(h);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxHabitacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxEmpleado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Cliente:");

        cbxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Habitacion:");

        cbxHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tblServicios);

        jLabel3.setText("Servicio Adicional:");

        jLabel4.setText("Factura N°:");

        jLabel5.setText("Empleado encargado:");

        cbxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardar.setText("Guardar y Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregarServicio.setText("Agregar Servicio");
        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(58, 58, 58)
                .addComponent(btnCancelar)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarServicio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(47, 47, 47)
                            .addComponent(cbxHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(cbxEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarServicio)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxClienteActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        // TODO add your handling code here:
        ArrayList<ServicioAdicional> disponibles = servicioDao.leer();
        
        if (disponibles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay servicios registrados.");
            return;
        }
        Object seleccion = JOptionPane.showInputDialog(
                this, "Seleccione servicio:", "Agregar",
                JOptionPane.QUESTION_MESSAGE, null,
                disponibles.toArray(), disponibles.get(0)
        );
        if (seleccion != null) {
            ServicioAdicional serv = (ServicioAdicional) seleccion;
            serviciosSeleccionados.add(serv);
            DefaultTableModel model = (DefaultTableModel) tblServicios.getModel();
            model.addRow(new Object[]{
                serv.getCodigoServicio(), 
                serv.getNombre(),     
                serv.getCategoria(),    
                serv.getDescripcion(),    
                serv.getPrecio()        
            });
            
            totalVisual += serv.getPrecio();
        }
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (txtNumFactura.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Falta el número de factura.");
                return;
            }
            
            Cliente cli = (Cliente) cbxCliente.getSelectedItem();
            int indiceHab = cbxHabitacion.getSelectedIndex();
                 if (indiceHab == -1) {
                    JOptionPane.showMessageDialog(this, "Seleccione una habitación.");
            return;
            }
            Habitacion hab = listaHabitacionesCombo.get(indiceHab);
            int indiceEmp = cbxEmpleado.getSelectedIndex();
                if (indiceEmp == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un empleado.");
            return;
            }
            Empleado emp = listaEmpleadosCombo.get(indiceEmp);
            
            Hotel.DTO.Factura f = new Hotel.DTO.Factura();
            f.setNumeroFacturas(txtNumFactura.getText());
            f.setFecha("11/02/2026"); 
            f.setClienteAsociado(cli);
            f.setHabitacionesAsocionadas(hab);
            f.setEmpleadoAsociado(emp); 
            f.setServiceAdicional(serviciosSeleccionados);
            f.calcularTotal(); 
            if (facturaDao.registrar(f)) {

                hab.setEstado("Ocupada");
                JOptionPane.showMessageDialog(this, "Factura Generada.\nTotal a Pagar: $" + f.getPrecioTotal());
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El número de factura ya existe.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this,"¿Estás seguro de cancelar?\n Los datos no guardados se perderan.","Confirmar cancelar",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose();
    }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Object[] opciones = {"Sí, salir", "No, quedarme"};
    
        int eleccion = javax.swing.JOptionPane.showOptionDialog(
            this,
            "¿Estás seguro de cerrar? Se perderán los datos no guardados.",
            "Confirmar Salida",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE,
            null,
            opciones,
            opciones[1]);

        if (eleccion == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxEmpleado;
    private javax.swing.JComboBox<String> cbxHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtNumFactura;
    // End of variables declaration//GEN-END:variables
}
