/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JFrame;

/**
 *
 * @author boris
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        System.out.println("Sistema iniciado correctamente.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuRegCliente = new javax.swing.JMenuItem();
        mnuBusCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuRegEmpleado = new javax.swing.JMenuItem();
        mnuBusEmpleado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuRegHabitacion = new javax.swing.JMenuItem();
        mnuBusHabitacion = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuRegServicio = new javax.swing.JMenuItem();
        mnuBusServicio = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuRegFactura = new javax.swing.JMenuItem();
        mnuBusFactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Gestión Hotelera - Grupo 1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PerroWasaa.png"))); // NOI18N

        jMenu1.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        mnuRegCliente.setText("Registrar cliente");
        mnuRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuRegCliente);

        mnuBusCliente.setText("Buscar clientes");
        mnuBusCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuBusCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleados");

        mnuRegEmpleado.setText("Registrar empleado");
        mnuRegEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegEmpleadoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuRegEmpleado);

        mnuBusEmpleado.setText("Buscar empleados");
        mnuBusEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusEmpleadoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuBusEmpleado);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Habitaciones");

        mnuRegHabitacion.setText("Registrar habitacion");
        mnuRegHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegHabitacionActionPerformed(evt);
            }
        });
        jMenu4.add(mnuRegHabitacion);

        mnuBusHabitacion.setText("Buscar habitaciones");
        mnuBusHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusHabitacionActionPerformed(evt);
            }
        });
        jMenu4.add(mnuBusHabitacion);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Servicios");

        mnuRegServicio.setText("Registrar servicio");
        mnuRegServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegServicioActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegServicio);

        mnuBusServicio.setText("Buscar servicios");
        mnuBusServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusServicioActionPerformed(evt);
            }
        });
        jMenu5.add(mnuBusServicio);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Facturacion");

        mnuRegFactura.setText("Registrar factura");
        mnuRegFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegFacturaActionPerformed(evt);
            }
        });
        jMenu6.add(mnuRegFactura);

        mnuBusFactura.setText("Buscar facturas");
        mnuBusFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBusFacturaActionPerformed(evt);
            }
        });
        jMenu6.add(mnuBusFactura);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setBounds(0, 0, 508, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir del sistema?");
            if(confirm == javax.swing.JOptionPane.YES_OPTION){
            System.exit(0);
}
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegClienteActionPerformed
        // TODO add your handling code here:
        Ventanaregistrocliente v = new Ventanaregistrocliente();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuRegClienteActionPerformed

    private void mnuBusClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusClienteActionPerformed
        // TODO add your handling code here:
        VentanaBusquedaCliente v = new VentanaBusquedaCliente();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuBusClienteActionPerformed

    private void mnuRegEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaRegistroEmpleado v = new VentanaRegistroEmpleado();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuRegEmpleadoActionPerformed

    private void mnuBusEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaBusquedaEmpleado v = new VentanaBusquedaEmpleado();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuBusEmpleadoActionPerformed

    private void mnuRegHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegHabitacionActionPerformed
        // TODO add your handling code here:
        VentanaRegistroHabitacion v = new VentanaRegistroHabitacion();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuRegHabitacionActionPerformed

    private void mnuBusHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusHabitacionActionPerformed
        // TODO add your handling code here:
        VentanaBusquedaHabitacion v = new VentanaBusquedaHabitacion();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuBusHabitacionActionPerformed

    private void mnuRegServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegServicioActionPerformed
        // TODO add your handling code here:
        VentanaRegistroServicio v = new VentanaRegistroServicio();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuRegServicioActionPerformed

    private void mnuBusServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusServicioActionPerformed
        // TODO add your handling code here:
        VentanaBusquedaServicio v = new VentanaBusquedaServicio();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuBusServicioActionPerformed

    private void mnuRegFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegFacturaActionPerformed
        // TODO add your handling code here:
        VentanaRegistroFactura v = new VentanaRegistroFactura();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuRegFacturaActionPerformed

    private void mnuBusFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBusFacturaActionPerformed
        // TODO add your handling code here:
        VentanaBusquedaFactura v = new VentanaBusquedaFactura();
            v.setVisible(true);
            v.setLocationRelativeTo(null);
            v.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_mnuBusFacturaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Object[] opciones = {"Salir", "Cancelar"};
    
        int eleccion = javax.swing.JOptionPane.showOptionDialog(
            this,
            "¿Estás seguro de salir? Se perderán los datos no guardados.",
            "Confirmar Salida",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE,
            null,
            opciones,
            opciones[1]);

        if (eleccion == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuBusCliente;
    private javax.swing.JMenuItem mnuBusEmpleado;
    private javax.swing.JMenuItem mnuBusFactura;
    private javax.swing.JMenuItem mnuBusHabitacion;
    private javax.swing.JMenuItem mnuBusServicio;
    private javax.swing.JMenuItem mnuRegCliente;
    private javax.swing.JMenuItem mnuRegEmpleado;
    private javax.swing.JMenuItem mnuRegFactura;
    private javax.swing.JMenuItem mnuRegHabitacion;
    private javax.swing.JMenuItem mnuRegServicio;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
