
package Vista;

public class VentanaBusquedaEmpleado extends javax.swing.JFrame {

    public VentanaBusquedaEmpleado() {
        initComponents();
        this.setTitle("Busqueda de Empleados - Hotel Grupo 1");
        actualizarTabla();
    }
    private void actualizarTabla() {
    try {
        Hotel.DAO.EmpleadoDAO dao = new Hotel.DAO.EmpleadoDAO();
        
        java.util.ArrayList<Hotel.DTO.Empleado> lista = dao.leerTodos();
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEmpleados.getModel();
        
        modelo.setRowCount(0);

        for (Hotel.DTO.Empleado emp : lista) {
            Object[] fila = {
                emp.getCedula(),
                emp.getApellido(),
                emp.getNombre(),
                emp.getCargo(),
                emp.getTurno(),
                emp.getSueldo()
            };
            modelo.addRow(fila);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBusquedaApellido = new javax.swing.JTextPane();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        btnDespedir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Busqueda de empleados contratados");
        jLabel1.setToolTipText("");

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Apellidos", "Nombres", "Cargo", "Turno", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        jLabel2.setText("Apellidos del Empleado:");

        jScrollPane2.setViewportView(txtBusquedaApellido);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        btnDespedir.setText("Despedir Seleccionado");
        btnDespedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnMostrarTodos)
                        .addGap(124, 124, 124)
                        .addComponent(btnDespedir)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarTodos)
                            .addComponent(btnDespedir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String apellidoBusqueda = txtBusquedaApellido.getText().trim().toLowerCase();

    if (apellidoBusqueda.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un apellido para buscar.");
        return;
    }

    try {
        Hotel.DAO.EmpleadoDAO dao = new Hotel.DAO.EmpleadoDAO();
        java.util.ArrayList<Hotel.DTO.Empleado> listaCompleta = dao.leerTodos();
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEmpleados.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla para mostrar solo resultados

        boolean encontrado = false;
        for (Hotel.DTO.Empleado emp : listaCompleta) {
            if (emp.getApellido().toLowerCase().contains(apellidoBusqueda)) {
                Object[] fila = {
                    emp.getCedula(),
                    emp.getApellido(),
                    emp.getNombre(),
                    emp.getCargo(),
                    emp.getTurno(),
                    emp.getSueldo()
                };
                modelo.addRow(fila);
                encontrado = true;
            }
        }

        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron empleados con el apellido: " + apellidoBusqueda);
            actualizarTabla(); 
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error durante la búsqueda: " + e.getMessage());
    }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespedirActionPerformed
        // TODO add your handling code here:
        int fila = tblEmpleados.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione al empleado que desea despedir.");
        return;
    }

    String cedula = tblEmpleados.getValueAt(fila, 0).toString();
    String apellido = tblEmpleados.getValueAt(fila, 1).toString();

    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea despedir al empleado " + apellido + " con cedula " + cedula + "?", 
            "Confirmar Despido", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        try {
            Hotel.DAO.EmpleadoDAO dao = new Hotel.DAO.EmpleadoDAO();
            
            java.util.ArrayList<Hotel.DTO.Empleado> lista = dao.leerTodos();

            lista.removeIf(emp -> emp.getCedula().equals(cedula));

            dao.guardarLista(lista);

            actualizarTabla();

            javax.swing.JOptionPane.showMessageDialog(this, "El empleado ha sido eliminado del sistema exitosamente.");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar el despido: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDespedirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Desea cerrar la ventana de búsqueda de empleados?", 
            "Confirmar salida", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose(); 
    }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBusquedaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBusquedaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBusquedaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBusquedaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBusquedaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDespedir;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextPane txtBusquedaApellido;
    // End of variables declaration//GEN-END:variables
}
